version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mercury-mongodb
    environment:
      MONGO_INITDB_DATABASE: mercury-erp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mercury-app
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}  # This will read from .env file
      - PORT=${PORT}
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongodb_data: